
    create table items (
       id bigint not null,
        name varchar(255),
        removed boolean default false,
        quote_id bigint,
        primary key (id)
    );

    create table quote_log (
       id bigint generated by default as identity,
        created_date timestamp,
        error_code integer,
        message varchar(255),
        operation INTEGER,
        quote_id bigint,
        primary key (id)
    );

    create table quotes (
       id bigint not null,
        name varchar(255),
        price double not null,
        removed boolean default false,
        primary key (id)
    );

    create table user (
       id bigint generated by default as identity,
        account_non_expired boolean not null,
        account_non_locked boolean not null,
        credentials_non_expired boolean not null,
        enabled boolean not null,
        password varchar(255),
        username varchar(255) not null,
        primary key (id)
    );

    create table user_custom_authorities (
       user_custom_id bigint not null,
        authorities integer
    );

    alter table quotes
       add constraint UK_quotes_name_unique unique (name);

    alter table user 
       add constraint UK_user_username_unique unique (username);

    alter table items 
       add constraint FK_items_quotes
       foreign key (quote_id) 
       references quotes;

    alter table user_custom_authorities 
       add constraint FK_user_custom_authorities_user
       foreign key (user_custom_id) 
       references user;
